### ISSUE TITLE
I cant see why a PsrConnectionFactory interface is needed.

### ISSUE THREAD

**Issue by prisis** [queue-interop/queue-interop#5]
Can you tell me why a PsrConnectionFactory interface is needed?
Psr should be easy and slim

**Comment by makasim** [comment]
It abstracts context creation logic and it is part of jms spec

**Comment by prisis** [comment]
I read the jms spec, but is a 100% port of the jms spec needed for php?

If you take a look on the cache psr there is no factory interface at all.

Note: Is just a question, not a criticism.

**Comment by makasim** [comment]
The connection factory abstracts the way connection is established with MQ broker. For example, it could be a stream or socket. It actually tries to connect to the broker. Manages credentials and other options.  I've found it very handy ever since we added it. 

Take a look at any of the factory implementations, especially createContext method. You find there a code which good to have abstracted.
